version: "3.8"

services:
  orchestrator:
    build:
      context: "."
      dockerfile: "./Orchestrator/Dockerfile"
    ports:
      - "32000:32000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Realise
        
  persistence:
    build:
      context: "."
      dockerfile: "./DAL/Dockerfile"
    ports:
      - "32100:32100"
    environment:
      - ASPNETCORE_ENVIRONMENT=Realise
  
  api:
    build:
      context: "."
      dockerfile: "./Api/Dockerfile"
    ports:
      - "32200:32200"
    environment:
      - ASPNETCORE_ENVIRONMENT=Realise