version: "3.8"

services:
  orchestrator:
    build:
      context: "./Orchestrator"
      dockerfile: "Dockerfile"
    ports:
      - "32000:32000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Realise